name: Build and Test Docker Image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: |
          docker build -t flask-web-app .
      - name: Run Flask application in Docker container
        run: |
          docker run -d -p 5000:5000 flask-web-app
          sleep 10 
      - name: Run simple test (curl)
        run: |
          curl http://127.0.0.1:5000/hello/test > result.txt
          echo "Test result:"
          cat result.txt
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            aquasec/flask-web-app:latest
          push: true
