name: CI Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: |
          docker build -t flask-app .
      - name: Install Trivy
        run: |
          curl -Lo trivy https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-x86_64
          chmod +x trivy
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy scan on Docker image
        run: |
          trivy image --exit-code 1 --no-progress flask-app

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            aquasec/flask-app:latest
            aquasec/flask-app:${{ github.ref_name }}
          push: true
      - name: Run simple test
        run: |
          curl http://127.0.0.1:5000/hello/test > result.txt
          echo "Test result:"
          cat result.txt
