name: CI Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: |
          docker build -t flask-web-app .
      - name: Verify the image build (non-test verification)
        run: |
          docker images | grep flask-web-app
          echo "Docker image built successfully."
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            aquasec/flask-web-app:latest
          push: true
